### ISSUE TITLE
Possible to audit multiple URLs in Nuxt Application?

### ISSUE THREAD

**Issue by t1mwillis** [samturrell/nuxt-lighthouse-module#3]
Hi! Thanks so much for your work on this package, looks very useful. I've successfully gotten it setup with my nuxt application, but I'm curious if you might support auditing multiple URLs in an application as opposed to just the `APP_URL`? I could see this being an array in the config that is used, otherwise it falls back on `process.env.APP_URL`.

**Comment by samturrell** [comment]
Hi @t1mwillis - sounds like a good idea. Happy to accept a PR for this change. Unfortunately i don't have time to do it myself, and I no longer use this module on my projects.

**Comment by t1mwillis** [comment]
@samturrell thanks for getting back. We decided to move in a different direction, instead running lighthouse tests as part of our larger CI/CD pipeline in Jenkins. I'll go ahead and close this issue.
